
package org.example.soapclient;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TodoServiceImpl", targetNamespace = "http://service.example.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TodoServiceImpl {


    /**
     * 
     * @return
     *     returns java.util.List<org.example.soapclient.Todo>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllTodos", targetNamespace = "http://service.example.org/", className = "org.example.soapclient.GetAllTodos")
    @ResponseWrapper(localName = "getAllTodosResponse", targetNamespace = "http://service.example.org/", className = "org.example.soapclient.GetAllTodosResponse")
    @Action(input = "http://service.example.org/TodoServiceImpl/getAllTodosRequest", output = "http://service.example.org/TodoServiceImpl/getAllTodosResponse")
    public List<Todo> getAllTodos();

    /**
     * 
     * @param arg0
     * @return
     *     returns org.example.soapclient.Todo
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTodoById", targetNamespace = "http://service.example.org/", className = "org.example.soapclient.GetTodoById")
    @ResponseWrapper(localName = "getTodoByIdResponse", targetNamespace = "http://service.example.org/", className = "org.example.soapclient.GetTodoByIdResponse")
    @Action(input = "http://service.example.org/TodoServiceImpl/getTodoByIdRequest", output = "http://service.example.org/TodoServiceImpl/getTodoByIdResponse")
    public Todo getTodoById(
        @WebParam(name = "arg0", targetNamespace = "")
        Long arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "updateTodoStatus", targetNamespace = "http://service.example.org/", className = "org.example.soapclient.UpdateTodoStatus")
    @ResponseWrapper(localName = "updateTodoStatusResponse", targetNamespace = "http://service.example.org/", className = "org.example.soapclient.UpdateTodoStatusResponse")
    @Action(input = "http://service.example.org/TodoServiceImpl/updateTodoStatusRequest", output = "http://service.example.org/TodoServiceImpl/updateTodoStatusResponse")
    public void updateTodoStatus(
        @WebParam(name = "arg0", targetNamespace = "")
        Long arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        boolean arg1);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "updateTodo", targetNamespace = "http://service.example.org/", className = "org.example.soapclient.UpdateTodo")
    @ResponseWrapper(localName = "updateTodoResponse", targetNamespace = "http://service.example.org/", className = "org.example.soapclient.UpdateTodoResponse")
    @Action(input = "http://service.example.org/TodoServiceImpl/updateTodoRequest", output = "http://service.example.org/TodoServiceImpl/updateTodoResponse")
    public void updateTodo(
        @WebParam(name = "arg0", targetNamespace = "")
        Todo arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "addTodo", targetNamespace = "http://service.example.org/", className = "org.example.soapclient.AddTodo")
    @ResponseWrapper(localName = "addTodoResponse", targetNamespace = "http://service.example.org/", className = "org.example.soapclient.AddTodoResponse")
    @Action(input = "http://service.example.org/TodoServiceImpl/addTodoRequest", output = "http://service.example.org/TodoServiceImpl/addTodoResponse")
    public void addTodo(
        @WebParam(name = "arg0", targetNamespace = "")
        Todo arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "deleteTodo", targetNamespace = "http://service.example.org/", className = "org.example.soapclient.DeleteTodo")
    @ResponseWrapper(localName = "deleteTodoResponse", targetNamespace = "http://service.example.org/", className = "org.example.soapclient.DeleteTodoResponse")
    @Action(input = "http://service.example.org/TodoServiceImpl/deleteTodoRequest", output = "http://service.example.org/TodoServiceImpl/deleteTodoResponse")
    public void deleteTodo(
        @WebParam(name = "arg0", targetNamespace = "")
        Long arg0);

}
