
package org.example.soapclient;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TodoServiceImplService", targetNamespace = "http://service.example.org/", wsdlLocation = "http://localhost:3334/todoService?wsdl")
public class TodoServiceImplService
    extends Service
{

    private final static URL TODOSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException TODOSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName TODOSERVICEIMPLSERVICE_QNAME = new QName("http://service.example.org/", "TodoServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:3334/todoService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TODOSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        TODOSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public TodoServiceImplService() {
        super(__getWsdlLocation(), TODOSERVICEIMPLSERVICE_QNAME);
    }

    public TodoServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), TODOSERVICEIMPLSERVICE_QNAME, features);
    }

    public TodoServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, TODOSERVICEIMPLSERVICE_QNAME);
    }

    public TodoServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TODOSERVICEIMPLSERVICE_QNAME, features);
    }

    public TodoServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TodoServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TodoServiceImpl
     */
    @WebEndpoint(name = "TodoServiceImplPort")
    public TodoServiceImpl getTodoServiceImplPort() {
        return super.getPort(new QName("http://service.example.org/", "TodoServiceImplPort"), TodoServiceImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TodoServiceImpl
     */
    @WebEndpoint(name = "TodoServiceImplPort")
    public TodoServiceImpl getTodoServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.example.org/", "TodoServiceImplPort"), TodoServiceImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TODOSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw TODOSERVICEIMPLSERVICE_EXCEPTION;
        }
        return TODOSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
